docker: prefer apt-get for py deps
I believe that the versions of the Python deps required by the test rig
can be satisfied through system packages. This avoids a pip error like:

```
 > [debian-sid  4/13] RUN pip install pytest tqdm pycurl cryptography:
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
------
failed to solve: process "/bin/sh -c pip install pytest tqdm pycurl cryptography" did not complete successfully: exit code: 1
```

If it turns out these versions are too old we can restore the `pip`
usage, but tweaked to avoid the above error.